# config.toml

# The default provider URL for the Rootstock network.
# Use the mainnet or testnet public node as needed.
[network]
name = "Testnet"
rpc_url = "https://public-node.testnet.rsk.co"
explorer_url = "https://explorer.testnet.rsk.co"

# Optionally, you can add other configuration options here.
# For example, a default wallet address or data directory:
# wallet_address = "0xYourWalletAddressHere"
# data_dir =