name: CI

on:
  push:
    branches: [ main, master, feat/* ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run tests
      run: cargo test --verbose
      
    - name: Check formatting
      run: |
        cargo fmt -- --check || {
          echo "Code is not formatted. Running cargo fmt..."
          cargo fmt
          echo "Code has been formatted. Please commit the changes."
          exit 1
        }
      
    - name: Run clippy
      run: cargo clippy -- -D warnings
      
    - name: Build release
      run: cargo build --release --verbose
